/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ouvidoria;

import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author N0026925
 */
public class attach_mail extends javax.swing.JPanel {

    Menu mn;
    JFileChooser jfc;
    int id;
    tratar tr;
    String cop_rec;
    int ifl_n3;

    /**
     * Creates new form attach_mail
     */
    public attach_mail() {

    }

    public attach_mail(int id, tratar tr, String cop_rec, int pifl_n3) {
        initComponents();

        final JFileChooser jfc = new JFileChooser(System.getProperty("user.home") + "\\Desktop");
        //this.add(jfc);
        this.jfc = jfc;
        this.mn = mn;
        this.id = id;
        this.tr = tr;
        this.cop_rec = cop_rec;
        this.ifl_n3 = pifl_n3;

        int returnVal = jfc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = jfc.getSelectedFile();
            anexar(file);

        }

    }

    public attach_mail(Novo_Registro_panel nr, String cop_rec, int pifl_n3) {
        initComponents();

        final JFileChooser jfc = new JFileChooser(System.getProperty("user.home") + "\\Desktop");
        //this.add(jfc);
        this.jfc = jfc;
        this.cop_rec = cop_rec;
        this.ifl_n3 = pifl_n3;

        int returnVal = jfc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = jfc.getSelectedFile();
            nr.set_file_attach(file.toString());

        }

    }

    public attach_mail(Novo_Registro_bsod nr, String cop_rec) {
        initComponents();

        final JFileChooser jfc = new JFileChooser(System.getProperty("user.home") + "\\Desktop");
        //this.add(jfc);
        this.jfc = jfc;
        this.cop_rec = cop_rec;

        int returnVal = jfc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = jfc.getSelectedFile();
            nr.set_file_attach(file.toString());

        }

    }

    public void anexar(File fl) {

        CopyOption[] options = new CopyOption[]{
            StandardCopyOption.REPLACE_EXISTING,
            StandardCopyOption.COPY_ATTRIBUTES
        };

        Path source = Paths.get(fl.getPath());
        //ALTERAR_BCC_OK
        Path dest = Paths.get("\\\\10.5.9.180\\GRVCOPCC$\\NET\\Ouvidoria - " + id + ".msg");
        try {
            java.nio.file.Files.copy(source, dest, options);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection conn = Db_class.mysql_conn();

            String query = "UPDATE painel SET mail_attach = 'Sim'"
                    + "WHERE id = " + tr.current_id;

            Db_class.mysql_insert(query, conn);

            Db_class.close_conn(conn);

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(attach_mail.class.getName()).log(Level.SEVERE, null, ex);
        }

        tr.insert_obs(tr.get_obs_hist() + "Anexado e-mail de acompanhamento.");

        tr.set_ult_acomp();

        global.show_message("E-mail anexado com sucesso!");

        tr.dispose();

        tratar tr_2 = new tratar(mn, true, tr.current_id, tr.pn, 0, cop_rec, ifl_n3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
