/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ouvidoria;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author N0026925
 */
public class baixa_os_n3 extends javax.swing.JDialog {

    tratar tr;

    List<Integer> liChave_acomp_status = new ArrayList<>();
    List<Integer> liChave_acomp_acao = new ArrayList<>();

    /**
     * Creates new form baixa_os
     */
    public baixa_os_n3(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public baixa_os_n3(java.awt.Frame parent, boolean modal, tratar tr, String cop) {
        super(parent, modal);
        initComponents();

        this.tr = tr;

        liChave_acomp_status = global.fill_combo_key(jcb_acomp_status,
                "select id, nome "
                + "from ouvidoria.tb_acao_acomp_status "
                + "where fl_ativo = 1 "
                + "order by nome ",
                true,
                1,
                2
        );

        global.open_modal(this, "Baixa de OS (N3)");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrp_bx_tec = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obs_baixa = new javax.swing.JTextArea();
        jbtn_confirmar_baixa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcb_acomp_status = new javax.swing.JComboBox();
        jcb_acomp_acao = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jrb_ass_conf_bx_tec_sim = new javax.swing.JRadioButton();
        jrb_ass_conf_bx_tec_nao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Observação");

        obs_baixa.setColumns(20);
        obs_baixa.setLineWrap(true);
        obs_baixa.setRows(1);
        obs_baixa.setWrapStyleWord(true);
        jScrollPane1.setViewportView(obs_baixa);

        jbtn_confirmar_baixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        jbtn_confirmar_baixa.setText("Confirma Baixa");
        jbtn_confirmar_baixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmar_baixaActionPerformed(evt);
            }
        });

        jLabel4.setText("Status Acomp");
        jLabel4.setToolTipText("Esse é o código de baixa no N3");

        jLabel5.setText("Ação Acomp");

        jcb_acomp_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_acomp_status.setToolTipText("Esse é o código de baixa no N3");
        jcb_acomp_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_acomp_statusActionPerformed(evt);
            }
        });

        jcb_acomp_acao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Assinante Confirma Baixa Técnica?");

        btgrp_bx_tec.add(jrb_ass_conf_bx_tec_sim);
        jrb_ass_conf_bx_tec_sim.setText("Sim");

        btgrp_bx_tec.add(jrb_ass_conf_bx_tec_nao);
        jrb_ass_conf_bx_tec_nao.setText("Não");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jcb_acomp_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_acomp_acao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrb_ass_conf_bx_tec_sim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrb_ass_conf_bx_tec_nao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_confirmar_baixa)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_acomp_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_acomp_acao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jrb_ass_conf_bx_tec_sim)
                        .addComponent(jrb_ass_conf_bx_tec_nao))
                    .addComponent(jbtn_confirmar_baixa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_confirmar_baixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmar_baixaActionPerformed

        if (jcb_acomp_status.getSelectedIndex() <= 0) {
            global.show_error_message("Selecione um Status Acomp");
            return;
        }

        if (jcb_acomp_acao.getSelectedIndex() <= 0) {
            global.show_error_message("Selecione um Ação Acomp");
            return;
        }

        if (!jrb_ass_conf_bx_tec_sim.isSelected() && !jrb_ass_conf_bx_tec_nao.isSelected()) {
            global.show_error_message("É necessário confirmar se o assinante aceita ou não a Baixa Técnica");
            return;
        }

        this.dispose();

        tr.finaliza_os_n3(obs_baixa.getText(),
                liChave_acomp_status.get(jcb_acomp_status.getSelectedIndex() - 1),
                liChave_acomp_acao.get(jcb_acomp_acao.getSelectedIndex() - 1),
                jcb_acomp_status.getItemAt(jcb_acomp_status.getSelectedIndex()).toString(),
                jcb_acomp_acao.getItemAt(jcb_acomp_acao.getSelectedIndex()).toString(),
                (jrb_ass_conf_bx_tec_sim.isSelected()?1:0)
        );

    }//GEN-LAST:event_jbtn_confirmar_baixaActionPerformed

    private void jcb_acomp_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_acomp_statusActionPerformed

        if (jcb_acomp_status.getSelectedIndex() > 0 && liChave_acomp_status.size() > 0) {
            liChave_acomp_acao = global.fill_combo_key(jcb_acomp_acao,
                    "select id, nome "
                    + "from ouvidoria.tb_acao_acomp_acao "
                    + "where fl_ativo = 1 "
                    + "and id_acomp_status = " + liChave_acomp_status.get(jcb_acomp_status.getSelectedIndex() - 1) + " "
                    + "order by nome ",
                    true,
                    1, 2
            );
        } else {
            jcb_acomp_acao.removeAllItems();
        }

    }//GEN-LAST:event_jcb_acomp_statusActionPerformed

    /**
     * jbtn_confirmar_baixa args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baixa_os_n3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baixa_os_n3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baixa_os_n3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baixa_os_n3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                baixa_os_n3 dialog = new baixa_os_n3(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrp_bx_tec;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_confirmar_baixa;
    private javax.swing.JComboBox jcb_acomp_acao;
    private javax.swing.JComboBox jcb_acomp_status;
    private javax.swing.JRadioButton jrb_ass_conf_bx_tec_nao;
    private javax.swing.JRadioButton jrb_ass_conf_bx_tec_sim;
    private javax.swing.JTextArea obs_baixa;
    // End of variables declaration//GEN-END:variables
}
