/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ouvidoria;

import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.coderazzi.filters.gui.AutoChoices;
import net.coderazzi.filters.gui.TableFilterHeader;

/**
 *
 * @author N0026925
 */
public class consulta_divisao extends javax.swing.JPanel {

    Menu mn;

    /**
     * Creates new form consulta_divisao
     */
    public consulta_divisao(Menu mn) {
        initComponents();

        try {
            JTable tab = global.getTable("SELECT ifnull(ci_depara,'') as Cidade, "
                    + "ifnull(user_iat_manha,'') as 'IAT Manhã', "
                    + "ifnull(user_iat_tarde,'') as 'IAT Tarde', "
                    + "ifnull(user_epo_manha,'') as 'EPO Manhã', "
                    + "ifnull(user_epo_tarde,'') as 'EPO Tarde' "
                    + "FROM cidades_novo "
                    + "WHERE cop = 'COP NET' "
                    + "ORDER BY ci_depara ", jPanel1);

            for (int columnTable = 0; columnTable < tab.getColumnCount(); columnTable++) {

                tab.getColumnModel().getColumn(columnTable).setCellRenderer(new CustomRenderer());

            }

            TableFilterHeader filter = new TableFilterHeader(tab, AutoChoices.ENABLED);
            filter.setAdaptiveChoices(true);
            
        } catch (Exception ex) {
            Logger.getLogger(consulta_divisao.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    class CustomRenderer extends DefaultTableCellRenderer {

        private static final long serialVersionUID = 6703872492730589499L;

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cellComponent = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            if (isSelected) {

                cellComponent.setBackground(table.getSelectionBackground());
                cellComponent.setForeground(table.getSelectionForeground());
                table.setShowHorizontalLines(true);
                table.setShowVerticalLines(true);

            } else {

                cellComponent.setBackground(Color.WHITE);
                cellComponent.setForeground(table.getForeground());
                table.setShowHorizontalLines(true);
                table.setShowVerticalLines(true);

            }

            return cellComponent;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
