/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ouvidoria;

import java.net.ConnectException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import net.coderazzi.filters.gui.AutoChoices;
import net.coderazzi.filters.gui.TableFilterHeader;

/**
 *
 * @author N0026925
 */
public class div_turno extends javax.swing.JDialog {

    Menu mn;
    JTable main_tab;

    /**
     * Creates new form div_turno
     */
    public div_turno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public div_turno(Menu mn, boolean modal) {
        super(mn, modal);
        initComponents();

        this.mn = mn;

        atualiza_painel();

        global.open_modal(this, "Divisão de turnos");

    }

    public void atualiza_painel() {

        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();

        String query = "SELECT login, ifnull(nome, '') as Nome, ifnull(turno,'') as Turno "
                + "FROM users "
                + "WHERE cop = '" + mn.get_cop() + "' "
                + "and perfil = 2 "
                + "ORDER BY nome";
        try {

            JTable tab = global.getTable(query, jPanel1);

            int invisible_ids[] = {0};
            int column_widths[] = {0, 150, 150};

            global.hide_columns(invisible_ids, tab);
            global.adjust_columns(column_widths, tab);

            main_tab = tab;

            TableFilterHeader filter = new TableFilterHeader(main_tab, AutoChoices.ENABLED);
            filter.setAdaptiveChoices(true);

        } catch (Exception ex) {
            Logger.getLogger(div_turno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        cb_turno = new javax.swing.JComboBox();
        bt_atribuir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(4, 30));
        jToolBar1.setMinimumSize(new java.awt.Dimension(4, 30));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator2);

        jLabel1.setText("      Mude o turno do usuário selecionado  ");
        jToolBar1.add(jLabel1);

        cb_turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Manhã", "Tarde", "Noite", "Madrugada" }));
        jToolBar1.add(cb_turno);

        bt_atribuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock_red.png"))); // NOI18N
        bt_atribuir.setText("Atribuir");
        bt_atribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atribuirActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_atribuir);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_atribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atribuirActionPerformed

        String s_turno = cb_turno.getSelectedItem().toString().trim();

        if (!"".equals(s_turno)) {
            atribui_turno(s_turno);
        }

    }//GEN-LAST:event_bt_atribuirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        atualiza_painel();

    }//GEN-LAST:event_jButton4ActionPerformed

    public void atribui_turno(String turno) {
        try {
            int[] selected_rows = main_tab.getSelectedRows();

            if (selected_rows.length > 0) {
                Connection conn = Db_class.mysql_conn();
                for (int row : selected_rows) {

                    String login_usuario = (String) main_tab.getValueAt(row, 0);
                    String query = "UPDATE users "
                            + "SET turno = '" + turno + "' "
                            + "WHERE login = '" + login_usuario + "'";

                    Db_class.mysql_insert(query, conn);
                }

                Db_class.close_conn(conn);
                global.show_message("Atribuição de turno realizada");
                atualiza_painel();
            } else {
                global.show_message("Selecione ao menos um usuário para a troca de turno");
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
            Logger.getLogger(div_turno.class.getName()).log(Level.SEVERE, null, ex);
            global.show_error_message(
                    "Problemas com a troca de turno.\n\n"
                    + "Erro: " + ex.getMessage()
            );
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(div_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(div_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(div_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(div_turno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                div_turno dialog = new div_turno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atribuir;
    private javax.swing.JComboBox cb_turno;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
